package com.nnh.backend.persistence.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

@Entity
@Table(name = "employees")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Employee {

    /** Format: NNHE-xxxxxxx (7 random digits). Generated by EmployeeService. */
    @Id
    @Column(nullable = false, updatable = false, length = 12)
    private String id;

    @Column(nullable = false)
    private String name;

    @Column(unique = true, nullable = false)
    private String email;

    @Column(nullable = false)
    private String passwordHash;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private EmployeeRole role;

    @Builder.Default
    private boolean active = true;

    /** True until the employee changes their password for the first time. */
    @Column(nullable = false, columnDefinition = "boolean default true")
    @Builder.Default
    private boolean mustChangePassword = true;

    @CreationTimestamp
    private LocalDateTime createdAt;
}
